### ISSUE TITLE
inconsistency between documentation and actual container json

### ISSUE THREAD

**Issue by makingscience-andresvelasco** [google-marketing-solutions/gtm-boilerplate#8]
In the following README.md:
https://github.com/google-marketing-solutions/gtm-boilerplate/blob/main/google_tag_manager/README.md

Server Side google Tag Manager step #7:

Open the web container -> Tags -> Open [GA4 Configuration] All Pages - sGTM -> Edit -> and enter the URL of the server container.

And the figure below shows a GA4 tag.

However the actual tag is "Google Tag", so I added property server_container_url to hopefully achieve the same.

**Comment by tdsymonds** [comment]
Thanks for flagging this. It looks like [this announcement ](https://support.google.com/tagmanager/answer/13543899) has caused the change. I'll add this to the backlog and get it updated asap.
